server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhangweiwei?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 911119

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.j1904
